const food_List = [
  {
    id: 1,
    image: "Images/MILKSHAKE2.jfif",
    name: "Milk-Shake",
    category: "Milkshake",
    description:
      "Let your first meal set the tone for your day. Breakfast is the most important meal of the day.",
    price: 300,
  },
  {
    id: 2,
    image: "Images/chikoo-milkshake.jfif",
    name: "Chikoo Milk-Shake",
    category: "Milkshake",
    description:
      "Let your first meal set the tone for your day. Breakfast is the most important meal of the day.",
    price: 300,
  },
  {
    id: 3,
    image: "Images/vanila-milkshake.jfif",
    name: "Vanila Milk-Shake",
    category: "Milkshake",
    description:
      "Let your first meal set the tone for your day. Breakfast is the most important meal of the day.",
    price: 300,
  },
  {
    id: 4,
    image: "Images/choco-milkshake.jfif",
    name: "Choco Milk-Shake",
    category: "Milkshake",
    description:
      "Let your first meal set the tone for your day. Breakfast is the most important meal of the day.",
    price: 300,
  },
  {
    id: 5,
    image: "Images/pineapple-milkshake.jpg",
    name: "PineApple Milk-Shake",
    category: "Milkshake",
    description:
      "Let your first meal set the tone for your day. Breakfast is the most important meal of the day.",
    price: 300,
  },
  {
    id: 6,
    image: "Images/strawberry-milkshake.jfif",
    name: "Strawberry Milk-Shake",
    category: "Milkshake",
    description:
      "Let your first meal set the tone for your day. Breakfast is the most important meal of the day.",
    price: 300,
  },
  {
    id: 7,
    image: "Images/tea.jpg",
    name: "Tea",
    category: "High Tea",
    description: "milkshake is good for health",
    price: 300,
  },
  {
    id: 8,
    image: "Images/lunch.jfif",
    name: "Daal Chawal",
    category: "lunch",
    description: "I believe in stopping work and eating lunch",
    price: 300,
  },
  {
    id: 9,
    image: "Images/lunch2.jfif",
    name: "Salad",
    category: "Salad",
    description: "Salads are the real definition of ‘eat the rainbow.",
    price: 300,
  },
  {
    id: 10,
    image: "Images/hightea.jfif",
    name: "High Tea",
    category: "High Tea",
    description: "A cup of tea is a cup of peace.",
    price: 300,
  },
  {
    id: 11,
    image: "Images/golgappay.jfif",
    name: "Golgappay",
    category: "High Tea",
    description:
      "Good friends and great Golgappas are the key ingredients for a perfect day",
    price: 300,
  },
  {
    id: 12,
    image: "Images/dinner.jfif",
    name: "Broast",
    category: "",
    description:
      "Dinner is not just about food; its about the company we keep and the memories we create.",
    price: 300,
  },
  {
    id: 13,
    image: "Images/chowmein.jfif",
    name: "Chowmein",
    category: "Chineese",
    description: "The food is my love and my love is only for food.",
    price: 300,
  },
  {
    id: 14,
    image: "Images/momos.jpg",
    name: "Momos",
    category: "Chineese",
    description: "“Momo madness: one bite and you're hooked! 🥢",
    price: 300,
  },
  {
    id: 15,
    image: "Images/pizza.jfif",
    name: "Pizza",
    category: "Chineese",
    description:
      "Pizza is a circle. Pizza is my life. Pizza is the circle of life.",
    price: 300,
  },
  {
    id: 15,
    image: "Images/food_1.png",
    name: "Salad",
    category: "Salad",
    description: "Salads are the real definition of ‘eat the rainbow",
  },
  {
    id: 16,
    image: "Images/food_2.png",
    name: "Salad",
    category: "Salad",
    description: "Salads are the real definition of ‘eat the rainbow",
    price: 300,
  },
  {
    id: 17,
    image: "Images/food_5.png",
    name: "Lasagnea",
    category: "Chineese",
    description: "The food is my love and my love is only for food",
    price: 300,
  },
  {
    id: 18,
    image: "Images/food_7.png",
    name: "Roll",
    category: "High Tea",
    description: "Life is better with a little bit of butter on a warm roll.",
    price: 300,
  },
  {
    id: 19,
    image: "Images/food_9.png",
    name: "Dessert",
    category: "Dessert",
    description: "Life is short; eat dessert first!",
    price: 300,
  },
  {
    id: 20,
    image: "Images/food_12.png",
    name: "Ice-Cream",
    category: "Dessert",
    description: "count the memories, not the calories🍨.",
    price: 300,
  },
  {
    id: 21,
    image: "Images/food_13.png",
    name: "Sandwitch",
    category: "Sandwitch",
    description: "A sandwich a day keeps the hangry away!🥪",
    price: 300,
  },
  {
    id: 22,
    image: "Images/food_17.png",
    name: "Cup-Cake",
    category: "Dessert",
    description:
      "Desserts are the fairy tales of the kitchen—a happily ever after to any meal.",
    price: 300,
  },
  {
    id: 23,
    image: "Images/food_18.png",
    name: "Cheese-Cake",
    category: "Dessert",
    description:
      "Desserts are the fairy tales of the kitchen—a happily ever after to any meal🍰",
    price: 300,
  },
  {
    id: 24,
    image: "Images/food_19.png",
    name: "BlueBerry-Cake",
    category: "Dessert",
    description: "Desserts are the art of turning sugar into smiles.",
    price: 300,
  },
  {
    id: 25,
    image: "Images/food_24.png",
    name: "RiceWithEgg",
    category: "",
    description: "I believe in stopping work and eating lunch.",
    price: 300,
  },
  {
    id: 26,
    image: "Images/food_25.png",
    name: "Pasta",
    category: "Chineese",
    description:
      "Dinner is not just about food; its about the company we keep and the memories we create..",
    price: 300,
  },
  {
    id: 27,
    image: "Images/food_26.png",
    name: "Pasta",
    category: "Chineese",
    description:
      "Dinner is not just about food; its about the company we keep and the memories we create.",
    price: 300,
  },
  {
    id: 28,
    image: "Images/food_27.png",
    name: "Alferdo-Pasta",
    category: "Chineese",
    description:
      "Dinner is not just about food; its about the company we keep and the memories we create..",
    price: 300,
  },
];
export default food_List;
